# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '31 21 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'The issue had been stale for a long time. Closing the issue for now. You can reopen the issue.'
        stale-pr-message: 'The PR had been stale without much activity. Closing the issue for now. You can reopen the PR.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
